{% set name = "pyocr" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyocr-{{ version }}.tar.gz
  sha256: 61ac4f021a5ff312cbdc8d1f803c5697664eb5f98f98e28c02dbd401aa784b0a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - pillow
    - python >=3.4

test:
  imports:
    - pyocr
    - pyocr.libtesseract
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://openpaper.work/en/projects/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: A Python wrapper for Tesseract and Cuneiform
  description: |
    PyOCR is an optical character recognition (OCR) tool wrapper 
    for python. That is, it helps using various OCR tools from a 
    Python program. It has been tested only on GNU/Linux systems. 
    It should also work on similar systems (*BSD, etc). It may or 
    may not work on Windows, MacOSX, etc.
  doc_url: https://openpaper.work/en/projects/
  dev_url: https://gitlab.gnome.org/World/OpenPaperwork/pyocr

extra:
  recipe-maintainers:
    - jan-janssen
